### ISSUE TITLE
[PE-D][Tester E] Incorrect error message for `delete_assignment`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F11-1/tp#275]
![image.png](https://raw.githubusercontent.com/yanhwee/ped/main/files/7b441de2-b354-43ed-9161-faddd90e72c4.png)

When added an additional argument that it's not supposed to handle, the command error message display an "incorrect" error message?

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: yanhwee/ped#2

**Comment by lm-44** [comment]
Can fix.

**Comment by avrilmohh** [comment]
Already fixed
![image](https://github.com/user-attachments/assets/fae75081-6d69-4764-aa59-5ea9cdb8ecde)
