### ISSUE TITLE
[PE-D][Tester A] add_student Command Allows Duplicate Phone Numbers and Emails

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F11-1/tp#282]
![image.png](https://raw.githubusercontent.com/DKHB0207/ped/main/files/ff2c21ee-4eba-46cb-9596-75a930138f38.png)

Steps to Reproduce:

1. Open the application and ensure it contains a list of students.
2. Add a new student using the command add_student n/p p/123 e/help@test.com.
3. Add another student using the command add_student n/q p/123 e/help@test.com (reusing the same phone number and email).

Expected Behaviour: The application should reject entries with duplicate phone numbers or emails, as each student contact should ideally have unique contact information.

Actual Behaviour: The application allows multiple students to be added with the same phone number and email, creating duplicate entries.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: DKHB0207/ped#5

**Comment by lm-44** [comment]
Invalid
