### ISSUE TITLE
[PE-D][Tester D] edit_student command does not display the correct error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F11-1/tp#284]
## Description
The edit_student command, when given an invalid format of the prefixes, displays the wrong error message.

## Steps to Reproduce
1. Open the app
2. Enter `edit_student si/2 /p1234` where the prefix of phone number is wrong.
3. Observe that the error message displayed is the one indicating that the index is invalid.

## Expected Behavior
The error message displayed should be the one indicating that the prefix is invalid, or the command format is wrong.

## Screenshots

![image.png](https://raw.githubusercontent.com/marchjlim/ped/main/files/ff8a4258-ca69-4022-860c-aa1f9154d511.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: marchjlim/ped#8

**Comment by lm-44** [comment]
Duplicate

**Comment by avrilmohh** [comment]
already fixed
![image](https://github.com/user-attachments/assets/cb18208c-a182-4aa3-ba44-c23884dc7ee0)
