### ISSUE TITLE
[PE-D][Tester E] Invalid argument (with spacing) for `view_student` (and other commands) but it still works.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F11-1/tp#287]
![image.png](https://raw.githubusercontent.com/yanhwee/ped/main/files/122db232-6939-46ce-8fb4-031223ce7d0d.png)

A spacing between the number 11, i.e. "1 1" is not a valid input, but the program still parses it as a valid number. However, this is a minor issue.

Similarly this issue occurs for `delete_student`.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: yanhwee/ped#4

**Comment by lm-44** [comment]
Minor issue. Mention in UG
