### ISSUE TITLE
[PE-D][Tester C] Clarity of Assignment Index in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F11-1/tp#298]
There appears to be an UI image explaining what Assignment Index are and how to use them in the `Editing an Assignment` UG. However, they're only explained after the `Adding an Assignment` & `Deleting an Assignment` UG. This explanation could be better if it were done at the beginning instead, as the user would probably require this information at the beginning of Assignment Commands

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: S-K-Y-Light/ped#9

**Comment by lm-44** [comment]
Can fix
