### ISSUE TITLE
[PE-D][Tester A] Commands in DG not updated to reflect new formats

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F11-1/tp#305]
![image.png](https://raw.githubusercontent.com/DKHB0207/ped/main/files/3dac4c6b-4369-4e0a-a846-6748dc107996.png)

The commands for delete and add have been changed in the actual app to delete_student and add_student, which is not reflected here.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: DKHB0207/ped#9

**Comment by lm-44** [comment]
Remove entire section.
