### ISSUE TITLE
[PE-D][Tester D] Slight mistake in the Quick Start of the UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F11-1/tp#308]
## Details
In the Quick Start section, step 4 is not comprehensive, as it depends on which home folder the user puts the jar file in, from step 3. It may not necessarily be under the downloads folder, as step 4 is mentioning.

![image.png](https://raw.githubusercontent.com/marchjlim/ped/main/files/10da5c61-b002-44cc-abf1-d6b3acb2fb9a.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: marchjlim/ped#15

**Comment by lm-44** [comment]
Change command to correct notation
