### ISSUE TITLE
[PE-D][Tester E] Incorrect flow of use cases for `Add a student`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F11-1/tp#313]
![image.png](https://raw.githubusercontent.com/yanhwee/ped/main/files/e8a6fa07-5cde-4c03-af33-6464876606f9.png)

Extension 1b could be improved. After 1b1, the teacher adds the student again by providing a different tag. However, this doesn't change the student information, such that adding the student again will work. As demonstrated in the application, I have a command that adds a student with a pre-existing name but with different tag, but the application still doesn't allow to add the student. Which I believe is the intended and right way. So there's a missing check at 1b2. And the use case should not resume at step 2. But otherwise it's mainly fine 👍👍

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: yanhwee/ped#9

**Comment by lm-44** [comment]
Change
