### ISSUE TITLE
[PE-D][Tester B] Having same macros for different prefixes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F11-1/tp#314]
instead of ```delete_assignment si/INDEX ai/INDEX``` both having INDEX, we can perhaps do ```delete_assignment si/STUDENT_INDEX ai/ASSIGNMENT_INDEX``` to avoid confusion.

![image.png](https://raw.githubusercontent.com/Droas590/ped/main/files/103159ff-7a78-4bea-84b5-5f9de15a1f30.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Droas590/ped#9

**Comment by lm-44** [comment]
Invalid.

**Comment by avrilmohh** [comment]
both INDEX are parsed the same way - they have the same constraints
