### ISSUE TITLE
[PE-D][Tester D] Insufficient description of the edit_assignment command in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F11-1/tp#315]
## Description
The UG does not indicate that editing the maximum score of an assignment will mark it as unsubmitted. 

![image.png](https://raw.githubusercontent.com/marchjlim/ped/main/files/13b27813-36b4-48b0-a6dd-a4ed280b2304.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: marchjlim/ped#17

**Comment by lm-44** [comment]
Duplicate.

**Comment by avrilmohh** [comment]
different tester
