### ISSUE TITLE
[PE-D][Tester E] Application behaviour and use case mismatch for "Add remark"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F11-1/tp#316]
![image.png](https://raw.githubusercontent.com/yanhwee/ped/main/files/e24d2b09-0c1a-4e57-b680-1b6d4ddcaeca.png)

As indicated by the use case, 1b2, the application should ask user for confirmation. But this is not in the behaviour of the application.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: yanhwee/ped#10

**Comment by lm-44** [comment]
Change. Delete 1b2 1b3

**Comment by lm-44** [comment]
Delete entire 1b, as use case continues as per normal
