### ISSUE TITLE
[PE-D][Tester E] Documentation: Example invocation sequence for ViewStudentCommand: Missing arguments for parse()

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F11-1/tp#318]
![image.png](https://raw.githubusercontent.com/yanhwee/ped/main/files/d6fbde85-2330-44e3-a074-99e4e4751938.png)

`parse()` should take in an argument. Similarly for "view_student" argument should have an index.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: yanhwee/ped#11

**Comment by lm-44** [comment]
Invalid. Optional to put args.
