### ISSUE TITLE
[PE-D][Tester B] Incorrect error message for duplicate index

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F11-1/tp#321]
input : ```edit_student si/1 r/math r/math```
output: ```Index should be a non-zero unsigned integer and cannot be blank.```
expected output: ```There should only be one r/```

![image.png](https://raw.githubusercontent.com/Droas590/ped/main/files/f297a99a-8d05-427f-821e-6362331980cf.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Droas590/ped#12

**Comment by lm-44** [comment]
Put under Planned Enhancement. The use of invalid prefixes and the / characters will lead to unexpected behaviour.
